### ISSUE TITLE
Add some CSS styling

### ISSUE THREAD

**Issue by hayzey** [hayzey/todolist#3]
This project now has a usable HTML GUI thanks to the recent changes by @shivasheeshyadav, but pretty much no CSS. It could use some styling to make it look a little nicer.

This is open to anyone. Style it however you want.

**Comment by mattgd** [comment]
I'm on it!

**Comment by ykshinde** [comment]
is it ok if I also work on the CSS part, you can choose the one you like ;)

**Comment by mattgd** [comment]
@thetomja Go for it. It's your project, you should choose.

**Comment by hmelenok** [comment]
Hey please check my PR
